const resList = [
  {
    info: {
      id: "737028",
      name: "Kanti Sweets",
      cloudinaryImageId: "60852362443f64a0017818f01301cddb",
      locality: "Kaggadasapura",
      areaName: "C V Raman Nagar New",
      costForTwo: "₹200 for two",
      cuisines: ["Sweets"],
      avgRating: 4.6,
      veg: true,
      avgRatingString: "4.6",
      totalRatingsString: "500+",
      sla: {
        deliveryTime: 16,
        lastMileTravel: 1.3,
        slaString: "15-20 mins",
      },
    },
  },
  {
    info: {
      id: "289253",
      name: "BOX8 - Desi Meals",
      cloudinaryImageId: "69a061b7e0f951cef2b4947946f94ec6",
      locality: "Kaggadasapura",
      areaName: "C V Raman Nagar",
      costForTwo: "₹250 for two",
      cuisines: ["North Indian", "Biryani", "Thalis", "Home Food"],
      avgRating: 4.5,
      avgRatingString: "4.5",
      totalRatingsString: "1K+",
      sla: {
        deliveryTime: 18,
        lastMileTravel: 0.7,
        slaString: "13-23 mins",
      },
    },
  },
  {
    info: {
      id: "613822",
      name: "EatFit",
      cloudinaryImageId: "a564ace38895abd960157ac2a76aaf2a",
      locality: "Kaggadasapura Village",
      areaName: "Mahadevapura",
      costForTwo: "₹270 for two",
      cuisines: [
        "Chinese",
        "Healthy Food",
        "Tandoor",
        "Pizzas",
        "North Indian",
        "Thalis",
        "Biryani",
      ],
      avgRating: 4.1,
      avgRatingString: "4.1",
      totalRatingsString: "1K+",
      sla: {
        deliveryTime: 20,
        lastMileTravel: 0.9,
        slaString: "20-25 mins",
      },
    },
  },
  {
    info: {
      id: "169353",
      name: "Baskin Robbins - Ice Cream Desserts",
      cloudinaryImageId: "85ccae4e3576f9330af102c46ca85395",
      locality: "Basavanagar Main Road",
      areaName: "Mahadevapura",
      costForTwo: "₹200 for two",
      cuisines: ["Ice Cream", "Desserts"],
      avgRating: 4.7,
      veg: true,
      avgRatingString: "4.7",
      totalRatingsString: "1K+",
      sla: {
        deliveryTime: 20,
        lastMileTravel: 2.5,
        slaString: "20-25 mins",
      },
    },
  },
  {
    info: {
      id: "13225",
      name: "Corner House Ice Cream",
      cloudinaryImageId: "iomlahl1lex51s8xnyh7",
      locality: "NGE F Layout",
      areaName: "Banaswadi",
      costForTwo: "₹250 for two",
      cuisines: ["Ice Cream", "Desserts"],
      avgRating: 4.7,
      avgRatingString: "4.7",
      totalRatingsString: "10K+",
      sla: {
        deliveryTime: 29,
        lastMileTravel: 5,
        slaString: "25-30 mins",
      },
    },
  },
  {
    info: {
      id: "10828",
      name: "California Burrito",
      cloudinaryImageId: "c5zl1drlxojljm21pz2p",
      locality: "Outer Ring Road",
      areaName: "Mahadevpura",
      costForTwo: "₹400 for two",
      cuisines: [
        "Mexican",
        "American",
        "Salads",
        "Continental",
        "Keto",
        "Healthy Food",
      ],
      avgRating: 4.6,
      avgRatingString: "4.6",
      totalRatingsString: "5K+",
      sla: {
        deliveryTime: 31,
        lastMileTravel: 4.1,
        slaString: "30-35 mins",
      },
    },
  },
  {
    info: {
      id: "13730",
      name: "Beijing Bites",
      cloudinaryImageId: "ca0eb08d0635fd6da2e5a480fec897d0",
      locality: "CV Raman Nagar",
      areaName: "CV Raman Nagar",
      costForTwo: "₹450 for two",
      cuisines: ["Chinese", "Thai"],
      avgRating: 4.3,
      avgRatingString: "4.3",
      totalRatingsString: "10K+",
      sla: {
        deliveryTime: 20,
        lastMileTravel: 1.1,
        slaString: "15-20 mins",
      },
    },
  },
  {
    info: {
      id: "186087",
      name: "The Biryani Life",
      cloudinaryImageId: "ymeyunqgdza647yobtaf",
      locality: "FRMS LAND MARK APARTMENT",
      areaName: "Kaggadasapura",
      costForTwo: "₹250 for two",
      cuisines: [
        "Biryani",
        "Mughlai",
        "Lucknowi",
        "Hyderabadi",
        "Kebabs",
        "Desserts",
        "Beverages",
      ],
      avgRating: 3.6,
      avgRatingString: "3.6",
      totalRatingsString: "1K+",
      sla: {
        deliveryTime: 25,
        lastMileTravel: 1.3,
        slaString: "20-25 mins",
      },
    },
  },
  {
    info: {
      id: "246128",
      name: "Hotel Empire",
      cloudinaryImageId: "visisdwdnhzflxgsjpvl",
      locality: "Garudachar Palya",
      areaName: "Mahadevpura",
      costForTwo: "₹250 for two",
      cuisines: ["North Indian", "Kebabs", "Biryani"],
      avgRating: 4.1,
      avgRatingString: "4.1",
      totalRatingsString: "10K+",
      sla: {
        deliveryTime: 37,
        lastMileTravel: 4.8,
        slaString: "35-40 mins",
      },
    },
  },
  {
    info: {
      id: "239069",
      name: "McDonald's",
      cloudinaryImageId: "f62564e14944753903849c4ef673af4d",
      locality: "Virtous Mall",
      areaName: "KR Puram",
      costForTwo: "₹400 for two",
      cuisines: ["Burgers", "Beverages", "Cafe", "Desserts"],
      avgRating: 4.3,
      avgRatingString: "4.3",
      totalRatingsString: "5K+",
      sla: {
        deliveryTime: 32,
        lastMileTravel: 3.9,
        slaString: "30-35 mins",
      },
    },
  },
  {
    info: {
      id: "810328",
      name: "Polar bear",
      cloudinaryImageId: "438ceb57212cc8476461e9753643126f",
      locality: "Vignan Nagar",
      areaName: "CV Raman Nagar",
      costForTwo: "₹350 for two",
      cuisines: ["Ice Cream", "Ice Cream Cakes"],
      avgRating: 4.5,
      avgRatingString: "4.5",
      totalRatingsString: "20+",
      sla: {
        deliveryTime: 19,
        lastMileTravel: 1.5,
        slaString: "15-20 mins",
      },
    },
  },
  {
    info: {
      id: "653628",
      name: "Chinese Wok",
      cloudinaryImageId: "e0839ff574213e6f35b3899ebf1fc597",
      locality: "Phoenix Market City",
      areaName: "Mahadevapura",
      costForTwo: "₹250 for two",
      cuisines: ["Chinese", "Asian", "Tibetan", "Desserts"],
      avgRating: 4,
      avgRatingString: "4.0",
      totalRatingsString: "100+",
      sla: {
        deliveryTime: 43,
        lastMileTravel: 3.8,
        slaString: "40-45 mins",
      },
    },
  },
  {
    info: {
      id: "285116",
      name: "Dindigul Thalappakatti",
      cloudinaryImageId: "qcoeeteu67eei7wlomdp",
      locality: "Garudacharpalya",
      areaName: "Whitefield",
      costForTwo: "₹600 for two",
      cuisines: [
        "Biryani",
        "Barbecue",
        "South Indian",
        "Chinese",
        "North Indian",
      ],
      avgRating: 4.1,
      avgRatingString: "4.1",
      totalRatingsString: "5K+",
      sla: {
        deliveryTime: 29,
        lastMileTravel: 4.2,
        slaString: "25-30 mins",
      },
    },
  },
  {
    info: {
      id: "5167",
      name: "Theobroma",
      cloudinaryImageId: "63dd75492c47fcec191132b8eb299ea5",
      locality: "2nd stage",
      areaName: "Indiranagar",
      costForTwo: "₹400 for two",
      cuisines: ["Bakery", "Desserts", "Beverages"],
      avgRating: 4.6,
      favourite: true,
      avgRatingString: "4.6",
      totalRatingsString: "10K+",
      sla: {
        deliveryTime: 34,
        lastMileTravel: 5.6,
        slaString: "30-35 mins",
      },
    },
  },
  {
    info: {
      id: "457308",
      name: "Bakingo",
      cloudinaryImageId: "e28bacacd405a62eb7f61d4b929ff9d6",
      locality: "New Thipasandra",
      areaName: "Indiranagar",
      costForTwo: "₹300 for two",
      cuisines: ["Bakery", "Desserts", "Beverages", "Snacks"],
      avgRating: 4.4,
      avgRatingString: "4.4",
      totalRatingsString: "1K+",
      sla: {
        deliveryTime: 30,
        lastMileTravel: 5,
        slaString: "30-35 mins",
      },
    },
  },
];

export default resList;
